= Part 1: From app to OpenShift

This is Part 1 of a 2 part series of blogs that will help you bringing your applications into OpenShift.

OpenShift v3 allows you to deploy your application in the cloud (whether is private, public or hybrid doesn't mind). Typically, the PaaS vendor (OpenShift in this case) will provide with a set of predefined runtimes that a developer can use to deploy his application on top. This developer would not need to care about the infrastructure or the runtime setup or configuration, he would just need to focus on his application, and what runtime to use. The PaaS would take care of sewing it all together and running it. 

But then, we come to the fact that not all the runtimes are provided by the vendor, or that the usages of these runtimes are not suitable for every application type, and there is a need for the PaaS provider to facilitate these to their users.

As a PaaS provider you'll need to provide with:

* runtimes (a.k.a platforms)
* configured usages of the runtimes for applications

== Runtimes
As OpenShift v3 relies on containers, the runtimes will be base images that provide with the grounds foundation to deploy an application (provided by the user) on top, and also that are highly configurable so there is no need to provide one of such images for every use case. Instead a different configuration provided to the image will make the runtime work as desired.

OpenShift v3 provides with some base images certified and ready to use for:

* https://docs.openshift.com/enterprise/3.0/using_images/s2i_images/nodejs.html[Node.js]
* https://docs.openshift.com/enterprise/3.0/using_images/s2i_images/ruby.html[Ruby]
* https://docs.openshift.com/enterprise/3.0/using_images/s2i_images/perl.html[Perl]
* https://docs.openshift.com/enterprise/3.0/using_images/s2i_images/php.html[PHP]
* https://docs.openshift.com/enterprise/3.0/using_images/s2i_images/python.html[Python]
* https://docs.openshift.com/enterprise/3.0/using_images/xpaas_images/eap.html[JBoss Enterprise Application Platform]
* https://docs.openshift.com/enterprise/3.0/using_images/xpaas_images/a_mq.html[JBoss A-MQ]
* https://docs.openshift.com/enterprise/3.0/using_images/xpaas_images/jws.html[JBoss Web Server]

OpenShift provides with the ability to inject/layer/build source code into these images, as they are created for https://docs.openshift.com/enterprise/3.0/creating_images/s2i.html#overview[S2I (Source-2-Image)] purposes.

OpenShift V3 also provides some base images with database runtimes that can be used or extended:

* https://docs.openshift.com/enterprise/3.0/using_images/db_images/mysql.html[MySQL]
* https://docs.openshift.com/enterprise/3.0/using_images/db_images/postgresql.html[PostgreSQL]
* https://docs.openshift.com/enterprise/3.0/using_images/db_images/mongodb.html[MongoDB]

== Configured usages of the runtimes
OpenShift v3 provides with set of predefined runtime use cases, that are user configurable, and allow for the deployment of the user application.
These predefined runtimes are modeled as *OpenShift templates*.

In these sense, OpenShift provides (amongst others) with templates for:

* JEE application running on an EAP server
* JEE application running on an EAP server and using an ephemeral database 
* JEE application running on an EAP server and using a persistent database 
* Web application running on a Tomcat Container
* Web application running on a Tomcat Container and using an ephemeral database 
* Web application running on a Tomcat Container and using a persistent database 
* ActiveMQ brokers with ephemeral storage
* ActiveMQ brokers with persistent storage
* Ephemeral database
* Persistent database
* Instant apps for Perl, Python, Ruby, PHP, node.js

NOTE: Instant apps are preconfigured example applications where the application itself can not be user provided. Also known as a QuickStart

As you can probably guess, not all possible combinations and capabilities for a runtime or set of runtimes can be provided out of the box, and in many cases, the PaaS provider will have to create more of these for the end user.

=== What is a template
From the official https://docs.openshift.com/enterprise/3.0/architecture/core_concepts/templates.html[documentation] we can read:

_____
A template describes a set of objects that can be parameterized and processed to produce a list of objects for creation by OpenShift. The objects to create can include anything that users have permission to create within a project, for example services, build configurations, and deployment configurations. A template may also define a set of labels to apply to every object defined in the template.
_____

This means that typically in a template we will have:

* A set of resources that will be created as part of "creating/deploying" the template
* A set of values for the parameters defined in the template
* A set of labels to decorate the generated resources  

A template will be defined in json or yaml format, and will be loaded into OpenShift for user instantiation, also known as application creation. 

The templates can have installation scope (for every OpenShift project) or project scope (only for a specific project). 

=== Predefined templates, or deploy your application on OpenShift
Typically, the PaaS provider will provide with a set of predefined templates, that will cover all of the usages or typologies/topologies of applications that can be deployed on OpenShift. 

The set of predefined templates will be accessible through the CLI or through the Web console. 

When creating your application using one of these templates, the user will typically provide with the source for the code of the application and some other configuration, like the application name.  


=== Custom templates, or OpenShiftify your application
Another use case is when you have a typology/topology of application that does not fit into the provided templates, and you require (or the PaaS provider) to provide a template to model it. This will be the topic for the next article, a walkthrough in how to create a template for your application.

